from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 771, 391))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.nameradioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.nameradioButton.setGeometry(QtCore.QRect(20, 15, 121, 17))
        self.nameradioButton.setObjectName("nameradioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.nameradioButton)
        self.roomradioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.roomradioButton.setGeometry(QtCore.QRect(20, 56, 101, 17))
        self.roomradioButton.setObjectName("roomradioButton")
        self.buttonGroup.addButton(self.roomradioButton)
        self.personradioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.personradioButton.setGeometry(QtCore.QRect(20, 96, 111, 17))
        self.personradioButton.setObjectName("personradioButton")
        self.buttonGroup.addButton(self.personradioButton)
        self.name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(140, 10, 261, 31))
        self.name.setObjectName("name")
        self.roomcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.roomcomboBox.setGeometry(QtCore.QRect(140, 50, 261, 31))
        self.roomcomboBox.setObjectName("roomcomboBox")
        self.personcomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.personcomboBox.setGeometry(QtCore.QRect(140, 90, 261, 31))
        self.personcomboBox.setObjectName("personcomboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 130, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.invNumber = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.invNumber.setGeometry(QtCore.QRect(530, 10, 251, 31))
        self.invNumber.setObjectName("invNumber")
        self.invradioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.invradioButton.setGeometry(QtCore.QRect(420, 20, 121, 16))
        self.invradioButton.setObjectName("invradioButton")
        self.buttonGroup.addButton(self.invradioButton)
        self.editpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.editpushButton.setGeometry(QtCore.QRect(20, 130, 111, 31))
        self.editpushButton.setObjectName("editpushButton")
        self.delpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delpushButton.setGeometry(QtCore.QRect(140, 130, 111, 31))
        self.delpushButton.setObjectName("delpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Поиск оборудования"))
        self.nameradioButton.setText(_translate("MainWindow", "По наименованию"))
        self.roomradioButton.setText(_translate("MainWindow", "По кабинету"))
        self.personradioButton.setText(_translate("MainWindow", "По сотруднику"))
        self.pushButton.setText(_translate("MainWindow", "Найти"))
        self.invradioButton.setText(_translate("MainWindow", "По инв.номеру"))
        self.editpushButton.setText(_translate("MainWindow", "Изменить"))
        self.delpushButton.setText(_translate("MainWindow", "Удалить"))
